### ISSUE TITLE
Zkontrolovat metodu UserManager.delete(userIDd)

### ISSUE THREAD

**Issue by Relickus** [lukaskom/shiftify#30]
metoda i po vícenásobnym zavolani se stejnym userID nevyhazuje vyjimku. 

1) Nemelo by jit smazat víckrát stejnou osobu - měl bych dostat nějakou zpětnou vazbu že to nevyšlo, aspon tu vyjimku když nemá návratovou hodnotu.
2) Nemelo by jit smazat osobu s userID ktere v db neni.

Tohle ověř.

**Comment by lukaskom** [comment]
Nechme to na defaultním nastavení chování greenDaa a SQLite.
