### ISSUE TITLE
Link from "Rozpis směn pracovníků" to "Detail pracovníka"

### ISSUE THREAD

**Issue by lukaskom** [lukaskom/shiftify#38]
When selecting a person in "Rozpis směn pracovníků" view, the "Detail pracovníka" view should appear, not the "Rozpis šichet pracovníka".

**Comment by liferili** [comment]
https://github.com/lukaskom/shiftify/commit/edad96598a0e36096b2e17424ab289c4a9f67d80?diff=unified

**Comment by liferili** [comment]
Fixed in commit https://github.com/lukaskom/shiftify/commit/edad96598a0e36096b2e17424ab289c4a9f67d80

**Comment by liferili** [comment]
Fixed in commit https://github.com/lukaskom/shiftify/commit/edad96598a0e36096b2e17424ab289c4a9f67d80
