### ISSUE TITLE
Broken date selector, broken date printing in "Rozpis plánů šichet"

### ISSUE THREAD

**Issue by lukaskom** [lukaskom/shiftify#43]
When I select it, I see the first date being todays date, when I go ahead and change it, it doesn't change at all, or just changes somehow weirdly .. Just have a look at it..

Also when I select a month in the date picker, it selects the day of the month before the one I selected. = I select March 2nd, it selects February 2nd. Sometimes I select a date in 2016 and it prints the same date in 2017.

**Comment by liferili** [comment]
Fixed in commit https://github.com/lukaskom/shiftify/commit/9cb65d594720e56c7e7ecd2c95f5bfeefd516318
