### ISSUE TITLE
Application stops working after selecting option "Upravit údaje"

### ISSUE THREAD

**Issue by Zubcz** [lukaskom/shiftify#48]

**Comment by liferili** [comment]
@lukaskom @dude65 

java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.cvut.fit.shiftify/cz.cvut.fit.shiftify.PersonEditActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cz.cvut.fit.shiftify.data.models.User.getFirstName()' on a null object reference

**Comment by liferili** [comment]
Fixed in af2065f1f29d00ea367129f31a2fcfafc443f091
